src/SADMO.AppWeb/Controllers/AlmacenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SADMO.AppWeb.ViewModels;
using SADMO.Mantenimiento.Infraestructure.Data.Interfaces;

namespace SADMO.AppWeb.Controllers
{
    public class AlmacenController : Controller
    {
        private readonly IProducto productoRepositorio;
        private readonly IAlmacen almacenRepositorio;
        private readonly IStock stockRepoitorio;
        public AlmacenController(IProducto productoRepositorio
                                , IAlmacen almacenRepositorio
                                , IStock stockRepoitorio)
        {
            this.productoRepositorio = productoRepositorio;
            this.almacenRepositorio = almacenRepositorio;
            this.stockRepoitorio = stockRepoitorio;
        }
        public async Task<IActionResult> VerStock()
        {
            StockModel model = new StockModel();
            model.Almacenes = await almacenRepositorio.ObtenerAlmacenes();
            model.Productos = await productoRepositorio.ObtenerProductos();
            model.Movimientos = await stockRepoitorio.MostarStock();
            model.Stocks = (from x in model.Movimientos
                            where x.TipoOperacion == 0
                            select new Models.Stock()
                            {
                                NombreAlmacen = x.NombreAlmacen,
                                DescripcionProducto = x.DescripcionProducto,
                                CantidadStock = x.CantidadStock
                            }).ToList();


            return View(model);
        }
        public async Task<IActionResult> DetalleStock(string almacen,string producto)
        {
            StockDetalleModel model = new StockDetalleModel();
            var detalle = await stockRepoitorio.MostarStock();
            var detalleStocks = (from x in detalle
                                                              where x.NombreAlmacen == almacen &&
                                                              x.DescripcionProducto == producto &&
                                                              x.TipoOperacion != 0
                                                              select new Models.DetalleStock()
                                                              { 
                                                                  TipoOperacion = x.TipoOperacion == 1 ? "Ingreso" : "Salida",
                                                                  CantidadMovimiento = x.CantidadMovimiento,
                                                                  FechaCreacion = x.FechaCreacion,
                                                                  UsuarioCreacion = x.UsuarioCreacion
                                                              }).ToList();
            model.DetalleStock = detalleStocks;
            model.NombreAlmacen = almacen;
            model.DescripcionProducto = producto;
            return View(model);
           
        }

        [HttpGet]
        public async Task<JsonResult> TraerStock(string producto,string almacen) {

            var Movimientos = await stockRepoitorio.MostarStock();

            var model = (from x in Movimientos
                            where x.TipoOperacion == 0
                            && x.NombreAlmacen == almacen
                            && x.DescripcionProducto == producto
                            select new Models.Stock()
                            {
                                NombreAlmacen = x.NombreAlmacen,
                                DescripcionProducto = x.DescripcionProducto,
                                CantidadStock = x.CantidadStock
                            }).ToList(); 

            return Json(model);
        }
    }
}

src/SADMO.AppWeb/Controllers/RfidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using SADMO.AppWeb.ViewModels;
using SADMO.Mantenimiento.Domain;
using SADMO.Mantenimiento.Infraestructure.Data.Interfaces;

namespace SADMO.AppWeb.Controllers
{
    public class RfidController : Controller
    {
        private readonly IRfid rfidRepository;
        private readonly IConfiguration configuration;
        public RfidController(IRfid rfidRepository, IConfiguration configuration)
        {
            this.rfidRepository = rfidRepository;
            this.configuration = configuration;
        }
        public async Task<IActionResult> Index()
        {
            RfidModel model = new RfidModel();
            model.RFIDs = await rfidRepository.ListarRFID();
           
            return View(model);
        }
        public async Task<IActionResult> GrabarMovimiento(string RfidCodInterno, string rfidTag)
        {
            RfidModel model = new RfidModel();
            model.RFIDs = await rfidRepository.ListarRFID();
            string uriApi = configuration.GetValue<string>("urlAPI");
            ApiStockRequest request = new ApiStockRequest();
            request.CodigoInternoRFID = RfidCodInterno;
            request.EtiquetaRFID = rfidTag;
            ApiStockResponse responseModel = new ApiStockResponse();
            string responseApi;
            using (var httpClient = new HttpClient())
            {
                System.Net.Http.StringContent content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync(uriApi, content))
                {
                    responseApi = await response.Content.ReadAsStringAsync();
                    responseModel = JsonConvert.DeserializeObject<ApiStockResponse>(responseApi);
                }
            }
            return View(responseModel);
        }
        
    }
}

src/SADMO.AppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - sadmo</title>
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" />
    <link href="~/bootstrap/css/glyphicon.css" rel="stylesheet" />
    <link href="~/limonte-sweetalert2/sweetalert2.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/sidebar/style.css" />
    <link rel="stylesheet" href="~/css/sidebar/jquery.mCustomScrollbar.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/DatePickerX.css" />


    <!-- Font Awesome JS -->
    <script src="~/js/sidebar/solid.js"></script>
    <script src="~/js/sidebar/fontawesome.js"></script>
</head>
<body>
    <div class="wrapper">
        <!--sidebar-->
        <nav id="sidebar">
            <div id="dismiss">
                <i class="fas fa-arrow-left"></i>
            </div>

            <div class="sidebar-header" style="text-align:center">
                <img src="~/img/cubo.png" alt="logo" style="width:80px;height:100px" />
            </div>

            <ul class="list-unstyled components">
                <p>SADMO</p>
                <li class="active">
                    <a  asp-controller="Home" asp-action="Index">Inicio</a>
                </li>
                <li>
                    <a href="#sm_solte" data-toggle="collapse" aria-expanded="false">Solicitud de Tiempo de Entrega</a>
                    <ul class="collapse list-unstyled" id="sm_solte">
                        <li>
                            <a class="nav-link text-dark"  asp-controller="Solicitud" asp-action="BuscarVenta">Buscar Documento de Venta</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark"  asp-controller="Solicitud" asp-action="SolicitudEntrega">Buscar Sol. Tiempo de Entrega</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#sm_list" data-toggle="collapse" aria-expanded="false">Listados</a>
                    <ul class="collapse list-unstyled" id="sm_list">
                        <li>
                            <a href="#">Listado de Tiempo de Entrega</a>
                            <a href="#">Listado de Recojo de Mercadería</a>
                            <a href="#">Listado de Envío y Disponibilidad de Transporte</a>
                            <a href="#">Listado de Rutas de Despacho</a>
                            <a href="#">Listado de Orden de Pedido</a>
                            <a href="#">Listado de Orden de Pedido - Cliente</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#sm_orpe" data-toggle="collapse" aria-expanded="false">Orden de Pedido</a>
                    <ul class="collapse list-unstyled" id="sm_orpe">
                        <li>
                            <a asp-action="OrdenPedido" asp-controller="Solicitud">Buscar Orden de Pedido</a>
                            <a href="#">Detalle de Tipo de Corte</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#sm_prod" data-toggle="collapse" aria-expanded="false">Producto</a>
                    <ul class="collapse list-unstyled" id="sm_prod">
                        <li>
                            <a href="#">Buscar Producto</a>
                            <a asp-action="VerStock" asp-controller="Almacen">Stock</a>
                            <a asp-action="Index" asp-controller="Rfid">Monitor RFID</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#sm_mon" data-toggle="collapse" aria-expanded="false">Monitorización</a>
                    <ul class="collapse list-unstyled" id="sm_mon">
                        <li>
                            <a href="#">Producto</a>
                            <a asp-action="Monitor" asp-controller="Transporte">Transporte</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Sadmo</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        @*<partial name="_LoginPartial" /*@
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark"  asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>
                        </ul>
                    </div>

                </div>
            </nav>

            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <footer class="border-top footer text-muted">
                <div class="container" style="text-align:center">
                    <a  asp-controller="Home" asp-action="Index">&copy; Sistema de Administración de Despacho y Monitoreo - Sadmo 2020</a>
                </div>
            </footer>

        </div>

    </div>

    <div class="overlay"></div>

    <input id="Ref" type="hidden" value="@Url.Content("~")" />
    <script src="~/jquery/jquery.js"></script>
    <script src="~/bootstrap/js/bootstrap.js"></script>
    <script src="~/font-awesome/js/fontawesome.js"></script>
    <script src="~/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/limonte-sweetalert2/sweetalert2.js"></script>
    <script async defer type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCV5nCIY_zdtMBM2S7f6MAO6hcNe4WcpfQ"></script>
    <script src="~/content/Site.js"></script>



    
    <script src="~/js/sidebar/popper.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/sidebar/jquery.mCustomScrollbar.concat.min.js"></script>
    @RenderSection("Scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#dismiss, .overlay').on('click', function () {
                $('#sidebar').removeClass('active');
                $('.overlay').removeClass('active');
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').addClass('active');
                $('.overlay').addClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>

</body>
</html>